"""
AI Employee Vault - Filesystem Watcher
=======================================
Monitors a designated DropFolder for new files.
When a new file is detected, creates a structured markdown task file
in the Needs_Action/ folder for the AI Employee to process.

Usage:
    python filesystem_watcher.py

Press Ctrl+C to stop the watcher.
"""

import os
import time
from datetime import datetime, timezone
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# ============================================================
# CONFIGURATION
# ============================================================

# Path to the AI Employee Vault root directory
VAULT_PATH = r'D:\coding\Hackaton\hac_0\AI_Employee_Vault'

# Path to the folder being watched for new files
WATCH_FOLDER = r'D:\coding\Hackaton\hac_0\DropFolder'

# Destination folder for generated task files
NEEDS_ACTION_PATH = os.path.join(VAULT_PATH, 'Needs_Action')


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_file_extension(filename):
    """Extract the file extension (without dot) from a filename."""
    _, ext = os.path.splitext(filename)
    return ext.lstrip('.').lower() if ext else 'unknown'


def get_file_size_formatted(size_bytes):
    """Convert file size in bytes to a human-readable string."""
    if size_bytes < 1024:
        return f"{size_bytes} bytes"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    elif size_bytes < 1024 * 1024 * 1024:
        return f"{size_bytes / (1024 * 1024):.1f} MB"
    else:
        return f"{size_bytes / (1024 * 1024 * 1024):.1f} GB"


def determine_file_type(extension):
    """Determine the general category of a file based on its extension."""
    type_map = {
        # Documents
        'md': 'document', 'txt': 'document', 'pdf': 'document',
        'doc': 'document', 'docx': 'document', 'rtf': 'document',
        # Spreadsheets
        'csv': 'spreadsheet', 'xlsx': 'spreadsheet', 'xls': 'spreadsheet',
        # Images
        'png': 'image', 'jpg': 'image', 'jpeg': 'image',
        'gif': 'image', 'bmp': 'image', 'svg': 'image',
        # Code
        'py': 'code', 'js': 'code', 'html': 'code',
        'css': 'code', 'json': 'code', 'xml': 'code',
        # Data
        'sql': 'data', 'db': 'data', 'sqlite': 'data',
    }
    return type_map.get(extension, 'other')


def determine_priority(filename):
    """
    Check the filename for emergency keywords to assign priority.
    Keywords: urgent, asap, critical, important, deadline, emergency
    """
    emergency_keywords = ['urgent', 'asap', 'critical', 'important', 'deadline', 'emergency']
    filename_lower = filename.lower()

    for keyword in emergency_keywords:
        if keyword in filename_lower:
            return 'high'

    return 'normal'


def create_task_markdown(original_name, file_size, file_path):
    """
    Generate a structured markdown string with frontmatter and details
    for the detected file. This will be saved in Needs_Action/.
    """
    # Gather file metadata
    extension = get_file_extension(original_name)
    file_type = determine_file_type(extension)
    priority = determine_priority(original_name)
    timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    size_formatted = get_file_size_formatted(file_size)

    # Build the markdown content with frontmatter
    markdown = f"""---
type: {file_type}
original_name: {original_name}
size: {size_formatted}
detected: {timestamp}
status: pending
priority: {priority}
---

# File Detected: {original_name}

## File Details
- **Original Name:** {original_name}
- **File Type:** {file_type} (.{extension})
- **Size:** {size_formatted}
- **Priority:** {priority}
- **Detected At:** {timestamp}
- **Source Path:** {file_path}

## Suggested Actions
- [ ] Review file contents
- [ ] Categorize appropriately
- [ ] Process according to file type
- [ ] Update Dashboard
- [ ] Move to Done when complete
- [ ] Create log entry

## Notes
_Automatically generated by filesystem_watcher.py_
"""
    return markdown


# ============================================================
# WATCHER EVENT HANDLER
# ============================================================

class NewFileHandler(FileSystemEventHandler):
    """
    Custom event handler for watchdog.
    Listens for newly created or moved/renamed files in the watch folder
    and generates corresponding task files in Needs_Action/.

    Handles two scenarios:
    1. Direct file creation → on_created fires
    2. Write-to-tmp-then-rename → on_moved fires (tmp → final name)
    """

    # Extensions to ignore (temporary/system files)
    IGNORED_EXTENSIONS = {'.tmp', '.crdownload', '.part', '.swp', '.lock'}

    def _should_ignore(self, filename):
        """Check if file should be skipped (temp files, hidden files)."""
        _, ext = os.path.splitext(filename)
        if ext.lower() in self.IGNORED_EXTENSIONS:
            print(f"[{datetime.now().strftime('%H:%M:%S')}] SKIPPED (temp file): {filename}")
            return True
        # Skip hidden files (starting with dot or tilde)
        if filename.startswith('.') or filename.startswith('~'):
            print(f"[{datetime.now().strftime('%H:%M:%S')}] SKIPPED (hidden/temp): {filename}")
            return True
        return False

    def _process_file(self, file_path, event_type):
        """
        Core processing logic shared by on_created and on_moved.
        Creates a task markdown file in Needs_Action/ for the detected file.
        """
        original_name = os.path.basename(file_path)

        # Skip temporary and system files
        if self._should_ignore(original_name):
            return

        # Log detection to console with event type for debugging
        print(f"[{datetime.now().strftime('%H:%M:%S')}] [{event_type}] File detected: {original_name}")
        print(f"    → Full path: {file_path}")

        try:
            # Brief pause to ensure the file is fully written before reading size
            time.sleep(0.5)

            # Verify the file still exists (it may have been a transient temp file)
            if not os.path.exists(file_path):
                print(f"[{datetime.now().strftime('%H:%M:%S')}] SKIPPED: File no longer exists: {original_name}")
                print()
                return

            # Get file size (may be 0 if file is still being written)
            file_size = os.path.getsize(file_path)

            # Generate the task markdown content
            task_content = create_task_markdown(original_name, file_size, file_path)

            # Create the task filename using convention: FILE_originalname_date.md
            date_str = datetime.now().strftime('%Y-%m-%d')
            # Remove the original extension for the task filename
            name_without_ext = os.path.splitext(original_name)[0]
            task_filename = f"FILE_{name_without_ext}_{date_str}.md"

            # Full path for the task file in Needs_Action/
            task_filepath = os.path.join(NEEDS_ACTION_PATH, task_filename)

            # Check if task file already exists (avoid duplicates from create+move)
            if os.path.exists(task_filepath):
                print(f"[{datetime.now().strftime('%H:%M:%S')}] SKIPPED (duplicate): Task already exists for {original_name}")
                print()
                return

            # Write the task file
            with open(task_filepath, 'w', encoding='utf-8') as f:
                f.write(task_content)

            # Log success to console
            print(f"[{datetime.now().strftime('%H:%M:%S')}] Task created: {task_filename}")
            print(f"    → Saved to: Needs_Action/{task_filename}")
            print(f"    → Type: {determine_file_type(get_file_extension(original_name))}")
            print(f"    → Priority: {determine_priority(original_name)}")
            print()

        except PermissionError:
            # File may be locked by another process
            print(f"[{datetime.now().strftime('%H:%M:%S')}] ERROR: Permission denied for {original_name}")
            print(f"    → File may be locked by another process. Skipping.")
            print()

        except FileNotFoundError:
            # File may have been moved or deleted before we could process it
            print(f"[{datetime.now().strftime('%H:%M:%S')}] ERROR: File not found: {original_name}")
            print(f"    → File may have been moved or deleted. Skipping.")
            print()

        except Exception as e:
            # Catch-all for unexpected errors — log but don't crash
            print(f"[{datetime.now().strftime('%H:%M:%S')}] ERROR processing {original_name}: {str(e)}")
            print()

    def on_created(self, event):
        """Called when a file is directly created in the watched folder."""
        if event.is_directory:
            return
        self._process_file(event.src_path, "CREATED")

    def on_moved(self, event):
        """
        Called when a file is moved/renamed into the watched folder.
        This catches the common pattern where editors write to a .tmp file
        and then rename it to the final filename.
        """
        if event.is_directory:
            return
        print(f"[{datetime.now().strftime('%H:%M:%S')}] [MOVED] {os.path.basename(event.src_path)} → {os.path.basename(event.dest_path)}")
        self._process_file(event.dest_path, "MOVED")


# ============================================================
# MAIN EXECUTION
# ============================================================

def main():
    """
    Main function to set up and start the filesystem watcher.
    Creates necessary directories if they don't exist,
    then monitors the watch folder until interrupted.
    """
    # Ensure the watch folder exists (create if not)
    if not os.path.exists(WATCH_FOLDER):
        os.makedirs(WATCH_FOLDER)
        print(f"Created watch folder: {WATCH_FOLDER}")

    # Ensure the Needs_Action folder exists
    if not os.path.exists(NEEDS_ACTION_PATH):
        os.makedirs(NEEDS_ACTION_PATH)
        print(f"Created Needs_Action folder: {NEEDS_ACTION_PATH}")

    # Display startup banner
    print("=" * 60)
    print("  AI Employee Vault - Filesystem Watcher")
    print("  Bronze v0.1")
    print("=" * 60)
    print(f"  Watching:  {WATCH_FOLDER}")
    print(f"  Output:    {NEEDS_ACTION_PATH}")
    print(f"  Started:   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    print()
    print("Waiting for new files... (Press Ctrl+C to stop)")
    print()

    # Set up the watchdog observer with our custom handler
    event_handler = NewFileHandler()
    observer = Observer()

    # Schedule the observer to watch the folder (non-recursive)
    observer.schedule(event_handler, WATCH_FOLDER, recursive=False)

    # Start watching
    observer.start()

    try:
        # Keep the script running until Ctrl+C is pressed
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        # Graceful shutdown on Ctrl+C
        print()
        print(f"[{datetime.now().strftime('%H:%M:%S')}] Watcher stopped by user.")
        print("Shutting down...")
        observer.stop()

    # Wait for the observer thread to finish
    observer.join()
    print("Watcher terminated. Goodbye!")


# Entry point
if __name__ == '__main__':
    main()
