/**
 * Slack MCP Server v1.0
 * ======================
 * Tools: 5 — Team communication via Slack Web API
 * Part of the AI Employee Vault Gold Tier — Cross-Domain Integration
 *
 *   send_channel_message  → Post a message to a Slack channel (HITL approval)
 *   send_dm               → Send a direct message to a user (HITL approval)
 *   post_file             → Upload a file to a Slack channel (HITL approval)
 *   get_mentions          → Get messages where the bot was mentioned (read-only)
 *   create_reminder       → Create a Slack reminder for a user (HITL approval)
 *
 * All tools default to SIMULATION MODE — no real Slack API calls until
 * a Bot token is configured. See README.md for setup.
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// ============================================================
// CONFIGURATION
// ============================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// Vault root — two levels up from mcp_servers/slack_mcp/
const VAULT_PATH = path.resolve(__dirname, "..", "..");

// ── Simulation flag ───────────────────────────────────────────
// Set to false + set SLACK_BOT_TOKEN to go live.
const SIMULATE_SLACK = true;

// ── Slack credentials ─────────────────────────────────────────
const SLACK_BOT_TOKEN   = process.env.SLACK_BOT_TOKEN   || "";    // xoxb-...
const SLACK_TEAM_ID     = process.env.SLACK_TEAM_ID     || "";    // T...
const SLACK_BOT_USER_ID = process.env.SLACK_BOT_USER_ID || "";    // U...

// ── Default channels (configurable) ──────────────────────────
const DEFAULT_CHANNEL   = process.env.SLACK_DEFAULT_CHANNEL || "#general";
const TEAM_CHANNEL      = process.env.SLACK_TEAM_CHANNEL    || "#ai-employee";

// ── Slack API base ────────────────────────────────────────────
const SLACK_API_BASE = "https://slack.com/api";

// ============================================================
// UTILITIES
// ============================================================

function log(msg) {
  process.stderr.write(`[slack-mcp] ${msg}\n`);
}

function nowIso() {
  return new Date().toISOString();
}

function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

function generateId() {
  return Math.floor(Math.random() * 0xFFFFFFFF).toString(16).toUpperCase().padStart(8, "0");
}

function successResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    isError: false,
  };
}

function errorResult(message) {
  return {
    content: [{ type: "text", text: `ERROR: ${message}` }],
    isError: true,
  };
}

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
}

function expiresIso(hours = 24) {
  return new Date(Date.now() + hours * 3600 * 1000).toISOString();
}

// ============================================================
// APPROVAL FILE WRITERS
// ============================================================

function createSlackMessageApprovalFile(msg, type = "channel") {
  ensureDir(path.join(VAULT_PATH, "Pending_Approval"));
  const id       = generateId();
  const prefix   = type === "dm" ? "SLACK_DM" : "SLACK_MESSAGE";
  const filename = `${prefix}_${id}_${todayStr()}.md`;
  const filepath = path.join(VAULT_PATH, "Pending_Approval", filename);
  const expires  = expiresIso(24);

  const targetLabel = type === "dm"
    ? `Direct Message to: ${msg.user_id}`
    : `Channel: ${msg.channel}`;

  const threadNote = msg.thread_ts
    ? `\n**Thread reply to:** ${msg.thread_ts}`
    : "";

  const content = `---
type: slack_${type}_approval
action: slack_send_${type === "dm" ? "dm" : "message"}
message_id: ${id}
target: ${type === "dm" ? msg.user_id : msg.channel}
created: ${nowIso()}
expires: ${expires}
status: pending
risk_level: medium
requested_by: slack_mcp
simulation_mode: ${SIMULATE_SLACK}
---

# Approval Request: Slack ${type === "dm" ? "Direct Message" : "Channel Message"}

**${targetLabel}**${threadNote}

## Message Preview

---

${msg.message}

---

## Details
- **Mode:** ${SIMULATE_SLACK ? "SIMULATION — no real Slack API call" : "LIVE — Slack Web API chat.postMessage"}
- **Expires:** ${expires}

## To Approve → move to Approved/
## To Reject  → move to Rejected/

---
*Generated by slack_mcp — AI Employee Vault Gold Tier*
`;

  fs.writeFileSync(filepath, content, "utf-8");
  log(`Slack message approval file created: ${filename}`);
  return { id, filename, filepath };
}

function createSlackFileApprovalFile(upload) {
  ensureDir(path.join(VAULT_PATH, "Pending_Approval"));
  const id       = generateId();
  const filename = `SLACK_FILE_${id}_${todayStr()}.md`;
  const filepath = path.join(VAULT_PATH, "Pending_Approval", filename);
  const expires  = expiresIso(24);

  const content = `---
type: slack_file_upload_approval
action: slack_post_file
upload_id: ${id}
channel: ${upload.channel}
created: ${nowIso()}
expires: ${expires}
status: pending
risk_level: medium
requested_by: slack_mcp
simulation_mode: ${SIMULATE_SLACK}
---

# Approval Request: Upload File to Slack

**Channel:** ${upload.channel}
**File:** ${upload.file_path}
**Title:** ${upload.title || path.basename(upload.file_path)}

## Initial Comment
${upload.initial_comment || "(none)"}

## Details
- **Mode:** ${SIMULATE_SLACK ? "SIMULATION — no real Slack API call" : "LIVE — Slack Web API files.upload"}
- **Expires:** ${expires}

## To Approve → move to Approved/
## To Reject  → move to Rejected/

---
*Generated by slack_mcp — AI Employee Vault Gold Tier*
`;

  fs.writeFileSync(filepath, content, "utf-8");
  log(`Slack file upload approval created: ${filename}`);
  return { id, filename, filepath };
}

function createSlackReminderApprovalFile(reminder) {
  ensureDir(path.join(VAULT_PATH, "Pending_Approval"));
  const id       = generateId();
  const filename = `SLACK_REMINDER_${id}_${todayStr()}.md`;
  const filepath = path.join(VAULT_PATH, "Pending_Approval", filename);
  const expires  = expiresIso(24);

  const content = `---
type: slack_reminder_approval
action: slack_create_reminder
reminder_id: ${id}
user_id: ${reminder.user_id}
created: ${nowIso()}
expires: ${expires}
status: pending
risk_level: low
requested_by: slack_mcp
simulation_mode: ${SIMULATE_SLACK}
---

# Approval Request: Create Slack Reminder

**For user:** ${reminder.user_id}
**At:** ${reminder.time}

## Reminder Text

---

${reminder.text}

---

## Details
- **Mode:** ${SIMULATE_SLACK ? "SIMULATION — no real Slack API call" : "LIVE — Slack Web API reminders.add"}
- **Expires:** ${expires}

## To Approve → move to Approved/
## To Reject  → move to Rejected/

---
*Generated by slack_mcp — AI Employee Vault Gold Tier*
`;

  fs.writeFileSync(filepath, content, "utf-8");
  log(`Slack reminder approval created: ${filename}`);
  return { id, filename, filepath };
}

// ============================================================
// TOOL: send_channel_message
// ============================================================

async function sendChannelMessage(args) {
  const {
    channel = DEFAULT_CHANNEL,
    message,
    thread_ts = "",
    blocks = null,
  } = args;

  if (!message) return errorResult("message is required");

  log(`send_channel_message: channel=${channel}, SIMULATE=${SIMULATE_SLACK}`);

  const msgData = { channel, message, thread_ts, blocks };

  if (SIMULATE_SLACK) {
    const { id, filename, filepath } = createSlackMessageApprovalFile(msgData, "channel");
    return successResult({
      simulation: true,
      status: "pending_approval",
      message_id: id,
      target: { type: "channel", channel },
      preview: message.slice(0, 200),
      thread_ts: thread_ts || null,
      approval_file: filename,
      approval_path: filepath,
      message: `Slack message approval created. Move ${filename} to Approved/ to send.`,
      hitl_required: true,
    });
  }

  // PRODUCTION: POST https://slack.com/api/chat.postMessage
  return errorResult("LIVE mode not yet configured. Set SLACK_BOT_TOKEN and set SIMULATE_SLACK=false.");
}

// ============================================================
// TOOL: send_dm
// ============================================================

async function sendDm(args) {
  const {
    user_id,
    message,
  } = args;

  if (!user_id)  return errorResult("user_id is required (Slack user ID, e.g. U0123456789)");
  if (!message)  return errorResult("message is required");

  log(`send_dm: user=${user_id}, SIMULATE=${SIMULATE_SLACK}`);

  const msgData = { user_id, message };

  if (SIMULATE_SLACK) {
    const { id, filename, filepath } = createSlackMessageApprovalFile(msgData, "dm");
    return successResult({
      simulation: true,
      status: "pending_approval",
      message_id: id,
      target: { type: "dm", user_id },
      preview: message.slice(0, 200),
      approval_file: filename,
      approval_path: filepath,
      message: `Slack DM approval created. Move ${filename} to Approved/ to send.`,
      hitl_required: true,
    });
  }

  // PRODUCTION: open a DM channel first, then chat.postMessage
  // POST /api/conversations.open with users=[user_id]
  // Then POST /api/chat.postMessage with channel=dm_channel_id
  return errorResult("LIVE mode not yet configured. Set SLACK_BOT_TOKEN and set SIMULATE_SLACK=false.");
}

// ============================================================
// TOOL: post_file
// ============================================================

async function postFile(args) {
  const {
    channel = DEFAULT_CHANNEL,
    file_path,
    title = "",
    initial_comment = "",
  } = args;

  if (!file_path) return errorResult("file_path is required (relative to vault root)");

  log(`post_file: file="${file_path}" → ${channel}, SIMULATE=${SIMULATE_SLACK}`);

  const uploadData = { channel, file_path, title: title || path.basename(file_path), initial_comment };

  if (SIMULATE_SLACK) {
    const { id, filename, filepath } = createSlackFileApprovalFile(uploadData);
    return successResult({
      simulation: true,
      status: "pending_approval",
      upload_id: id,
      target: { channel },
      file: {
        local_path: file_path,
        title: uploadData.title,
        initial_comment,
      },
      approval_file: filename,
      approval_path: filepath,
      message: `Slack file upload approval created. Move ${filename} to Approved/ to post.`,
      hitl_required: true,
    });
  }

  // PRODUCTION: POST https://slack.com/api/files.upload (multipart/form-data)
  return errorResult("LIVE mode not yet configured. Set SLACK_BOT_TOKEN and set SIMULATE_SLACK=false.");
}

// ============================================================
// TOOL: get_mentions
// ============================================================

async function getMentions(args) {
  const {
    channel = "",
    max_results = 10,
    since_ts = "",
  } = args;

  log(`get_mentions: channel="${channel || "all"}", max=${max_results}, SIMULATE=${SIMULATE_SLACK}`);

  if (SIMULATE_SLACK) {
    const mockMentions = [
      {
        ts: "1740825600.000100",
        channel: "#ai-employee",
        user: "U0ALICE001",
        username: "alice",
        text: "<@AI_EMPLOYEE> can you generate this week's CEO briefing and post it in #leadership?",
        type: "message",
        permalink: "https://company.slack.com/archives/C0AIBOT001/p1740825600000100",
      },
      {
        ts: "1740736800.000200",
        channel: "#general",
        user: "U0BOB002",
        username: "bob",
        text: "<@AI_EMPLOYEE> please remind the team about the investor demo on Friday at 2pm",
        type: "message",
        permalink: "https://company.slack.com/archives/C0GENERAL/p1740736800000200",
      },
      {
        ts: "1740650400.000300",
        channel: "#engineering",
        user: "U0CAROL003",
        username: "carol",
        text: "<@AI_EMPLOYEE> what's the status of the outstanding approvals?",
        type: "message",
        permalink: "https://company.slack.com/archives/C0ENGINEER/p1740650400000300",
      },
    ]
    .filter(m => !channel || m.channel === channel)
    .slice(0, max_results);

    return successResult({
      simulation: true,
      bot_user_id: SLACK_BOT_USER_ID || "U_AI_EMPLOYEE (simulated)",
      filter: { channel: channel || "all channels", since_ts: since_ts || "last 7 days" },
      mentions_found: mockMentions.length,
      mentions: mockMentions,
      note: "SIMULATION MODE — set SIMULATE_SLACK=false + configure SLACK_BOT_TOKEN to read real mentions",
    });
  }

  // PRODUCTION: POST /api/search.messages with query "@bot_user_id"
  return errorResult("LIVE mode not yet configured. Set SLACK_BOT_TOKEN.");
}

// ============================================================
// TOOL: create_reminder
// ============================================================

async function createReminder(args) {
  const {
    text,
    time,
    user_id = "me",
  } = args;

  if (!text) return errorResult("text is required — the reminder message");
  if (!time) return errorResult("time is required — ISO 8601 datetime or relative (e.g. 'in 1 hour', 'tomorrow at 9am')");

  log(`create_reminder: user=${user_id}, time="${time}", SIMULATE=${SIMULATE_SLACK}`);

  const reminderData = { text, time, user_id };

  if (SIMULATE_SLACK) {
    const { id, filename, filepath } = createSlackReminderApprovalFile(reminderData);
    return successResult({
      simulation: true,
      status: "pending_approval",
      reminder_id: id,
      reminder: { text, time, user_id },
      approval_file: filename,
      approval_path: filepath,
      message: `Slack reminder approval created. Move ${filename} to Approved/ to set.`,
      hitl_required: true,
    });
  }

  // PRODUCTION: POST https://slack.com/api/reminders.add
  // Params: text, time (Unix epoch or relative string), user
  return errorResult("LIVE mode not yet configured. Set SLACK_BOT_TOKEN and set SIMULATE_SLACK=false.");
}

// ============================================================
// MCP SERVER SETUP
// ============================================================

const server = new Server(
  { name: "slack-mcp", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

// ── Tool definitions ──────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "send_channel_message",
      description: "Post a message to a Slack channel. Requires HITL approval before sending. Supports thread replies.",
      inputSchema: {
        type: "object",
        properties: {
          channel:   { type: "string",  description: "Channel name or ID (e.g. #general or C0123456789). Default: #general" },
          message:   { type: "string",  description: "Message text (supports Slack markdown)" },
          thread_ts: { type: "string",  description: "Thread timestamp to reply in a thread (optional)" },
          blocks:    { type: "array",   description: "Slack Block Kit blocks for rich formatting (optional)" },
        },
        required: ["message"],
      },
    },
    {
      name: "send_dm",
      description: "Send a direct message to a Slack user. Requires HITL approval before sending.",
      inputSchema: {
        type: "object",
        properties: {
          user_id: { type: "string", description: "Slack user ID (e.g. U0123456789) or username" },
          message: { type: "string", description: "Message text (supports Slack markdown)" },
        },
        required: ["user_id", "message"],
      },
    },
    {
      name: "post_file",
      description: "Upload a file from the vault to a Slack channel with an optional comment. Requires HITL approval.",
      inputSchema: {
        type: "object",
        properties: {
          channel:         { type: "string", description: "Channel to post to (default: #general)" },
          file_path:       { type: "string", description: "Path to file relative to vault root (e.g. Reports/CEO_Briefing_2026-02-23.md)" },
          title:           { type: "string", description: "File title in Slack (defaults to filename)" },
          initial_comment: { type: "string", description: "Message posted alongside the file (optional)" },
        },
        required: ["file_path"],
      },
    },
    {
      name: "get_mentions",
      description: "Get Slack messages where the AI Employee bot was @mentioned. Read-only — no HITL required.",
      inputSchema: {
        type: "object",
        properties: {
          channel:     { type: "string", description: "Limit to a specific channel (optional — default: all channels)" },
          max_results: { type: "number", description: "Maximum mentions to return (default: 10)" },
          since_ts:    { type: "string", description: "Only return mentions after this Slack timestamp (optional)" },
        },
      },
    },
    {
      name: "create_reminder",
      description: "Create a Slack reminder for a user. Requires HITL approval before creating.",
      inputSchema: {
        type: "object",
        properties: {
          text:    { type: "string", description: "Reminder message text" },
          time:    { type: "string", description: "When to send the reminder — ISO 8601 or relative (e.g. 'in 2 hours', 'tomorrow at 9am', '2026-03-01T09:00:00Z')" },
          user_id: { type: "string", description: "Slack user ID to remind (default: 'me' — the bot owner)" },
        },
        required: ["text", "time"],
      },
    },
  ],
}));

// ── Tool dispatcher ───────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args = {} } = request.params;
  log(`Tool called: ${name}`);
  try {
    switch (name) {
      case "send_channel_message": return await sendChannelMessage(args);
      case "send_dm":              return await sendDm(args);
      case "post_file":            return await postFile(args);
      case "get_mentions":         return await getMentions(args);
      case "create_reminder":      return await createReminder(args);
      default: return errorResult(`Unknown tool: ${name}`);
    }
  } catch (err) {
    log(`Error in tool ${name}: ${err.message}`);
    return errorResult(`Internal error: ${err.message}`);
  }
});

// ── Start ─────────────────────────────────────────────────────

const transport = new StdioServerTransport();
await server.connect(transport);

log("Slack MCP Server v1.0.0 started");
log(`Vault: ${VAULT_PATH}`);
log(`Mode: Slack=${SIMULATE_SLACK ? "SIMULATION" : "LIVE"}`);
log(`Default channel: ${DEFAULT_CHANNEL} | Team channel: ${TEAM_CHANNEL}`);
log("Tools: send_channel_message, send_dm, post_file, get_mentions, create_reminder");
